//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MINHTUANMOBILE
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietXuatKho
    {
        public string MaCTPX { get; set; }
        public string PhieuXuat { get; set; }
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public string DungLuong { get; set; }
        public string MauSac { get; set; }
        public string HeDieuHanh { get; set; }
        public Nullable<int> SoLuongXuat { get; set; }
        public string XuatDenCN { get; set; }
    
        public virtual SanPham SanPham { get; set; }
        public virtual XuatKho XuatKho { get; set; }
    }
}
