//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MINHTUANMOBILE
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHang()
        {
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
        }
    
        public string MaDH { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string MaKH { get; set; }
        public string TenKH { get; set; }
        public string TenNV { get; set; }
        public string MaTT { get; set; }
        public string PhuongThucTT { get; set; }
        public Nullable<System.DateTime> NgayTT { get; set; }
        public Nullable<double> TongTien { get; set; }
        public Nullable<double> TTMotPhan { get; set; }
        public Nullable<double> TienNo { get; set; }
        public string TrangThaiTT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual ThanhToan ThanhToan { get; set; }
    }
}
