//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MINHTUANMOBILE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_PN
    {
        public string PhieuNhap { get; set; }
        public string TenCN { get; set; }
        public string DiaChiCN { get; set; }
        public string SDTCN { get; set; }
        public string NguoiTao { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public string TenNCC { get; set; }
        public string DiaChiNCC { get; set; }
        public string SDTNCC { get; set; }
        public string TenSP { get; set; }
        public Nullable<double> GiaNhap { get; set; }
        public Nullable<double> ChietKhau { get; set; }
        public Nullable<double> ThanhTien { get; set; }
        public Nullable<int> SoLuongNhap { get; set; }
        public Nullable<double> TongTien { get; set; }
    }
}
