//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MINHTUANMOBILE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_DH
    {
        public string DiaChiCN { get; set; }
        public string SDTCN { get; set; }
        public string SDTKH { get; set; }
        public string DiaChiKH { get; set; }
        public string MaDH { get; set; }
        public string TenKH { get; set; }
        public string TenNV { get; set; }
        public string TenCN { get; set; }
        public string PhuongThucTT { get; set; }
        public string TenSP { get; set; }
        public Nullable<double> GiaBan { get; set; }
        public Nullable<int> SoLuongMua { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> ThanhTien { get; set; }
        public Nullable<double> TongTien { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
    }
}
