//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MINHTUANMOBILE
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
            this.ChiTietNhapKhoes = new HashSet<ChiTietNhapKho>();
            this.ChiTietXuatKhoes = new HashSet<ChiTietXuatKho>();
        }
    
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public string Hinh { get; set; }
        public string MaMau { get; set; }
        public string TenMau { get; set; }
        public string MaHDH { get; set; }
        public string TenHDH { get; set; }
        public string MaDL { get; set; }
        public string LoaiDL { get; set; }
        public string ManHinh { get; set; }
        public string MaLoaiSP { get; set; }
        public string TenLoaiSP { get; set; }
        public string MaNCC { get; set; }
        public string ThuongHieu { get; set; }
        public string MaCN { get; set; }
        public string TenCN { get; set; }
        public string BaoHanh { get; set; }
        public Nullable<double> GiaBan { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
    
        public virtual ChiNhanh ChiNhanh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietNhapKho> ChiTietNhapKhoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietXuatKho> ChiTietXuatKhoes { get; set; }
        public virtual DungLuong DungLuong { get; set; }
        public virtual HeDieuHanh HeDieuHanh { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
        public virtual MauSac MauSac { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
    }
}
